# Copyright 2014-2015 by Cloudsoft Corporation Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: required
language: java
jdk:
  - oraclejdk8

install: true
before_script:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - echo "Host localhost" >> /home/travis/.ssh/config
  - echo "    StrictHostKeyChecking no" >> /home/travis/.ssh/config
  - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
  - chmod g-rw,o-rw /home/travis/.ssh/*
  - mkdir -p ~/.brooklyn/docker-certs

script:
  - export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xmx2469m -XX:MaxPermSize=512m"
  - mkdir -p dist/target/brooklyn-maven-plugin/
  - touch dist/target/brooklyn-maven-plugin/brooklyn.debug.log
  - mvn -q clean verify -Pintegration -Dsoftlayer.identity=$SOFTLAYER_IDENTITY -Dsoftlayer.credential=$SOFTLAYER_CREDENTIAL
  - cat dist/target/brooklyn-maven-plugin/brooklyn.debug.log

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
  - secure: "BrRh52Ae8fkDqBRGOgFCi89DKDtTWnvZju3K1ntV0kC0nP0pIdKKKgCKZC9u8EmFYF8HZnHagqn3VSRX2+tASwo0xauY0urV4GlMUp38+Dnzt1Kg9XKL/m6aQdEu+EjhMm6KCar5CKZ1TdO36RWZdY6yM/0QZMSS6HqrdlDc8eo="
  - secure: "T8804sbwQgUGniJhfC/DdIwQ3Tt4UdyGVJWFzdVXKk+zSVm302PG1Ibp3A4kzMy9MUbYspRNh/lNmGsGN0DR1pElDqAO6zVDo7+KBaU7/gEoTjVigvhYcV1Y4E3X+KqXY1fykmLC4zjGpdmkWa602SX7EXpiJ0o31hujFXA3ElQ="
#  AWS
  - secure: "f0Jufx8S+6riOaScXbuXUudtEL5I+eyAZZd8xJzeGp9Zt9xvME+9Erjw1WyGV1g/64f+pfaKc2As39AD/FkY6PQmfnfUHKuudXnrHIAovkFZVwcBjlDNrrf5l1S3aJyjw2SkaA5bwOGlRF+h90fsjsZSD95jFIH4fWZDZo4FWXfE0s8fooWQyGKL77DT2AMWO5crkmo35YYM78PoLNKZTmf2cRJlUQU+qjgxdisQbABv6JotjGyQIqEudX6B0kwXJTpjb6hcBYDgvGTXIrKxzbO7ws3VbvGX3mKJq3G3RL/uJ8e7kJxJ7CaMErlrjO7GJkDQuHGyecYa5WlN2Skm88KHOUwnVmyTD4vB/WAZwsXcZ93cL+pBG880wMm64ge19W7N+Yt3iU1wL5XFGwt6XwWjEOjthQUW0XIv6t3LRUC9J1b4fT81GenO58VM5vOs3JghjY0cF2vQJ6Tl22pDwWoDVLCvQe5T5mnMH/TWZ3TYXeAnp0elMk6DZqWiS8RTFDMDi7ex5TntfCp2baDcswNzE8NsLPhJ74qyDkb9eFuDVVzW/o4nYhdYg9FBnPBBe6IAKyYWNgnRjNL9OTPhYnQxXsPrQ8ZHRbl0OTWBRndZ2oVIjTs43GbYwnbQSLuRrmWZN+XduTSPRdQC/U8I62wJKkuqSg3tr26doWIHR0I="
  - secure: "cqfjKBc4GwYOq4nUAT1br8DbdwYrbEbzpjzms0yvubJFwanl22tNDvd2mpAUoNbBTxvmDSTbMvBSFij3QV+PokW/t80sqXvH2CRVbHsKRBLMY7sqIfuazmO4bpO9QdFPpo21TizGWXF3c62AWP8eq9MGWxRF/UFV5/srYrzXbW8WLzbi0ixPItnrcwztILIwAlkHcyddHXol02t0G1OC3oSJzCvCjrjK/zZEi+2aF9R9vyZViUKUe+LeYT1lrdTSEOSPANahGDCtRU6PydMGs8hLNTNFp+eHLO7h1OxtE8//n/P5mES9qTo7m9GO/rwATTCjkbb7qQ6xWzzim6xMjFgx+rMBZEKzhE3hLMmvrLEINlGCrcNupyWFtNPBO/eW1+CEG72fbWq0qz3oBxzIy95RRNyUC+WxPCqp9jr5NJDI8H+d4ED4Pwweisc4/rZDKil5/lH+6eEWWbunXLo0SPVuXYfOXUeqZ72SIhqwPBfD9lGu7C+Tf5DIWgXsL7PEfaUhzKN+D392EuM1PwsUzIvCUqbUcKoJZ/17nmUQEVyxJnT+Ik+3hQwKRRvp7Vg6NeNrvmeshj0+19N2Gzh/QmQfQM4KSoNiP9YFFK3L15X2UqLodvH+9XNDIy/01zo3lwoqNgHpeCr8siKwIWerGIuxq1NYo8uC0sh7h5G90+A="


#  Test AMP Password
  - secure: "H7LFeJnJy7T7X8AijeaU1ILLGjbwqJyp+2GAt22CM6YdcrlaxFWtKfaHIZAhRJm3jDThhTAXThBr3qXO2relxpq0uvwvjW0f54+HUaKFp6OE2qGjdUbw/lLIT6DQ84r9tUOC335WE8QPZCdnTLd32+kZAVH4EnLS38f04+DHONrLv54PfTjpurnypCezoVp53s2oGVvqp0yPf09IqL57r47NCUrcHTTbM2dxdn4CzXCAjNnzO5gtUEsWY7mlWBg0lnzBfaZIt3JXcI8GqcrHfRZNSSBwreQASTca4dw5PAM5pUMi/A+1m3WKdMSH+DiEbWX+SgGKkxy565EYMdqgSGO18PPAdh15VPxDg6l6F+GlO58j4j05YRMfi4cw5WF54/FkLQzeH8/RmpTjfj+GpIs6XOWF2M68m06ceKAfdS31qI3xoP3c8DE5pgi4R3SKK8ddzG5P5V4k3tMFOsCg54g+LYnhzmTvwP7fok+Bd4q+m6goAl5g84V4OEzGmHhtkvorYQyO+FRwyA+oRH3G8yaVj2ljqOjHk83334x3RRVfZB7mLBJIRoVI4ZsFRu2j+0Nozy4JnVp++OcTtVn8I57rMRJAWzJqGyWM6r/UVI6JTGIcUWuNMH0AI+KMsqD1qlUXGUAS/XuCJJLUXyHScLhbPE+PIcMjgPJO6afz9ek="
#  Softlayer
  - secure: "HDTN8nYiOx+B8Wyvd/fcJGnTLq3zHx+56MhZGtfJN4DANObsLzGO24tO2zz23Gqu94Ivwz5VRKpScY8ZKwML+kcwajUUCtRQAnbJLRYCdZBct5/aaqbRAvfDvxgUPOJsLppInNGP7zSuAZoWkjWkP3cRP1GVgELDY6++wYrNa4+z+qixsm5Is4Df1q/LV+v7xOGZGCL2nd2dIHGdwWbMf+0fNu/IU6i9hi/b6YpmdmTIUi/0Dda3UtquZlnrnmml5FsU+mo+ZykLVrKn0/B+3U6seKTI+vkYtM+qlcX0RwSk3/hudBP0Nj9doZ16NOelVP1r7u9V0MR1Xt6obHKLxYlk/f/Uvzmv/TfhbY8UMEK0HOSSa1SsO5fYwXG1qaOzdRbdrXCJS2yGpn8P8cyN/g5GElSg7KMVFTuvSJ94xmPB6uUm9iXUdepYwfX2YhCBU3wKJkzU1xlTTXBa/rbAYUZ3mY9Le1kaItz4Ce6mPuikFfoWSX6XYEZHAzZoGN1TikA+xGmRSnlOqHsEb1MymWuuWsyfI3Euwh6mlvLTqod2GkzJRt4fAqKyVN2GQCUM7maF2YP0BSGEcGN0+YAdYwrT3NTm3yqcnbXdcxUXeY48O+jm1ObUeH2X6Sz/XTZC/pp4xGNy7oQtHbNPhhcK2i4ZBZpgvjFO7qNN0Ke7HLY="
  - secure: "hPkb8z84KYgPLy6uDSx3gcNgg2jxD6tlSS4nk3j3uEzz5QwJThglPUM1plerHrPFTqTDpZ5mOx+dWMxU6H81Yk2NZzV3JG2Ne0aSk69k6roD3LqGxPrbh3YpFr6go29QNgC971UuJJekM/RodBCE1Vjon4k+FkY1Ash2rKJrovFMhqP51NYqPysXxEDjJhYM7cLaJZV2SQ2jlPYXUAd5J4tgrCI1rOIa5gquiExIB868HDRF2GiFwqHqtYA/Y5npJMvpISvk70L3/6S9bqSw9vOvgFFMxmhKinrpDktN+Bm3kPWnNmx7pMrOFrQ46j6DoOViHpoGrqIDZbQoljCUst76oU82lHQZrkxTCx3bE9dc2atCg9NIWwTO4Pf31mjZ1uytNFNnqXK/UTwXUkJP908g5oDeB2JmbacFKJkPkTjc+diV96bm2YyLASzvKN1fT/7pftySRZ73Ngt2NSjdO62dx6xFZ6egP0P7vsEW+hrxPPjEfyjB2QEWr4EY7v1DZ47PU2mhbjFlaaA7sRuSQ5dO1vsyBz4s9OmsuihzlaxC1mYoOXrIItyD/+58Xyy3s6CpFqbSpaeQK5dFRNnhYeQh/rQIVYuj3CLk8SNIBPfTcnoGRq7rgWDQOlTS7Y0yyF7ZINIx5HmeTP9uLy28cO+8pbhj5Z2H09vDEO8ORwI="

# brooklyn.properties placeholders
  # SOFTALYER_IDENTITY=identity
  - secure: "PLv7B8XRUBGTTw+iXJ7H8+4ltThrL8P3Y7M5WKVgwwR2y84lLsqk3gcpPKj2+U3LtsGSg5sWqMXfHSLW79lST6S6JDZ/kXNi78YIfOYobR8at+efO7GoaRp/Qo0ticEvJUz4uSyZ69Nm7gjd0bxd4X/CbpG8wZjgt4RUYW6ny8k="
  # SOFTALYER_CREDENTIAL=credential
  - secure: "F/X34P2NlY/Efsmopr9U8E9Ewt3UpQguXZg/XmNYyClgwo3giC/iAkrnlEvwAGx1IeFn+QlYss8tsBn8za5IrquQKEZ2LiU8ommAx3RJdW2p1Pk6X5fhtz6kkJ3cHY/AvrJWs/bMxqQ2JcTWAfUkQKLH/6wxGy36HIZUpThdxIo="


cache:
  directories:
    - $HOME/.m2

notifications:
  email:
  - graeme.miller@cloudsoft.io
  - andrew.kennedy@cloudsoft.io
  - andrea.turli@cloudsoft.io
  slack: clocker:YcGvQVVHfwIzEogvQJzY2Xvi
