# Copyright 2014 by Cloudsoft Corporation Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

id: tomcat-application
name: "Tomcat Web Application"
origin: "http://brooklyncentral.github.io/"
locations:
- my-docker-cloud
services:
- serviceType: brooklyn.entity.webapp.tomcat.TomcatServer
  brooklyn.config:
    docker.dockerfile.url:
      "https://s3-eu-west-1.amazonaws.com/brooklyn-clocker/UsesJavaDockerfile"
    affinity.host.rules: |
      "NOT TYPE"
      "TYPE brooklyn.entity.nosql.solr.SolrServer"
      "SAME APPLICATION"
    wars.root:
      "https://s3-eu-west-1.amazonaws.com/brooklyn-clocker/hello-world.war"
    version: "7.0.53"
    jmx.enabled: true
    jmx.agent.mode: "JMXMP"
    jmx.direct.port: "30000+"
